// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZxbXYZTUfmbVJCk3iBlcDMLEzKh8HlZY',
    appId: '1:412468287121:web:b638271efa245a0ba9d130',
    messagingSenderId: '412468287121',
    projectId: 'docscanner-349e2',
    authDomain: 'docscanner-349e2.firebaseapp.com',
    storageBucket: 'docscanner-349e2.firebasestorage.app',
    measurementId: 'G-581DH6V7NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqbAn4lB6qAX2rffWOXMzx7m4Nf-mtDrY',
    appId: '1:412468287121:android:ecbdb683927d3a1ca9d130',
    messagingSenderId: '412468287121',
    projectId: 'docscanner-349e2',
    storageBucket: 'docscanner-349e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq2-1XdmX2HFxg1jwaEXcyoVALLZ8xTco',
    appId: '1:412468287121:ios:0102b6df96d26fd1a9d130',
    messagingSenderId: '412468287121',
    projectId: 'docscanner-349e2',
    storageBucket: 'docscanner-349e2.firebasestorage.app',
    androidClientId: '412468287121-qk61vh8v9rp8gtt0pfi6ocho54h4atap.apps.googleusercontent.com',
    iosClientId: '412468287121-8033bbkadj9nccrt5v02n6inesf05cet.apps.googleusercontent.com',
    iosBundleId: 'com.example.docforge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq2-1XdmX2HFxg1jwaEXcyoVALLZ8xTco',
    appId: '1:412468287121:ios:0102b6df96d26fd1a9d130',
    messagingSenderId: '412468287121',
    projectId: 'docscanner-349e2',
    storageBucket: 'docscanner-349e2.firebasestorage.app',
    androidClientId: '412468287121-qk61vh8v9rp8gtt0pfi6ocho54h4atap.apps.googleusercontent.com',
    iosClientId: '412468287121-8033bbkadj9nccrt5v02n6inesf05cet.apps.googleusercontent.com',
    iosBundleId: 'com.example.docforge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZxbXYZTUfmbVJCk3iBlcDMLEzKh8HlZY',
    appId: '1:412468287121:web:8ffb2dedb94f7b59a9d130',
    messagingSenderId: '412468287121',
    projectId: 'docscanner-349e2',
    authDomain: 'docscanner-349e2.firebaseapp.com',
    storageBucket: 'docscanner-349e2.firebasestorage.app',
    measurementId: 'G-933NM9FSHE',
  );

}